sudo: required
language: ruby
rvm:
  - 2.2
services:
  - mysql
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database ioh_rocks_test;'
script:
  - RAILS_ENV=test bundle exec rake db:reset
  - bundle exec rake db:test:prepare
  - bundle exec rspec
  - bundle exec rubocop
